import type { NextPage } from "next";
import Head from "next/head";
import { Fragment} from "react";
import CircleContainer from "../components/CircleContainer/CircleContainer";
import Content from "../components/Content/Content";
import RotatingNavigation from "../components/RotatingNavigation/RotatingNavigation";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossOrigin="anonymous"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <CircleContainer />
        <Content />
      </main>

      <RotatingNavigation />
    </Fragment>
  );
};

export default Home;
